#!/bin/sh

### Housekeeping
# Load new fonts.
#xset +fp /usr/share/fonts/local
xset fp rehash

# Merge xresources defaults.
~/bin/chxtheme dracula

# Skip most operations within KDE
if [ "$XDG_SESSION_DESKTOP" != "KDE" ]; then
	echo "continuing" >> xprofile.wtf
	# 🚫 caps lock.
	xmodmap .capscontrol
	nitrogen --restore &
	###

	### Daemons
	synclient PalmDetect=1
	synclient MaxTapTime=0
	synclient VertScrollDelta=-127 # natural scrolling
	sxhkd -c $HOME/.config/sxhkd/sxhkdrc & # Hotkeys
	start-pulseaudio-x11 & # Audio
	awesome-bat.fish &
	xss-lock -- i3lock -nt &
fi


