#!/bin/sh

### Housekeeping
# Load new fonts.
xset +fp /usr/share/fonts/local
xset fp rehash

# Merge xresources defaults.
$HOME/bin/xrr

# 🚫 caps lock.
xmodmap .capscontrol
#xmodmap .modswap
nitrogen --restore &
###

### Daemons
synclient PalmDetect=1
synclient MaxTapTime=0
synclient VertScrollDelta=-127 # natural scrolling
bard -c $HOME/.config/bard &
rescuetime & # time tracking
compton & # Compositing
touchegg & # Multitouch
sxhkd & # Hotkeys
#$HOME/bin/w3d & # CSS and JavaScript override server
autokey-gtk & # Text expansion
start-pulseaudio-x11 & # Audio

