#!/bin/sh

bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window-gap 6
bspc config split_ratio 0.52
bspc config bottom_padding 42

if bspc query -M | grep "HDM1" > /dev/null; then
	$HOME/bin/dualmon.sh
	bspc monitor eDP1 -d term chat mail root
	bspc monitor HDMI1 -d www dev bonus 5000
else
	bspc monitor -d term www chat dev mail bonus 5000 root
fi
