#!/bin/sh

bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window-gap 6
bspc config split_ratio 0.52
bspc config bottom_padding 20
bspc config status_prefix ""
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Firefox desktop=www
bspc rule -a Telegram desktop=chat

case $(hostname) in
	tauntaun)
		if xrandr | grep "^DP1 connected" > /dev/null; then
			$HOME/bin/dualmon.sh
		else
			$HOME/bin/solomon.sh
		fi
		;;
	totoro)
		;;
esac

